apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-binding
subjects:
  - kind: ServiceAccount
    name: eznft-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator
