apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator
rules:
  - apiGroups: ["batch"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    resources:
      - jobs