apiVersion: batch/v1
kind: Job
metadata:
  name: eznft
spec:
  template:
    spec:
      containers:
        - name: eznft
          args:
            - orchestrate
            - quick
            - --cpu
            - "300m"
            - --memory
            - "0.5Gi"
            - --args
            - "--target-override=http://example.com"
          imagePullPolicy: Never
          env:
            - name: MINIKUBE
              value: "true"
          resources:
            requests:
              cpu: "500m"
            limits:
              memory: "1Gi"