apiVersion: batch/v1
kind: Job
metadata:
  name: eznft
spec:
  template:
    spec:
      containers:
        - name: eznft
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: "3"
          image: eznft
          args:
            - orchestrate
            - slow
            - --pods
            - "18"
            - --image
            - "registry.tools.cosmic.sky/phoenix/test/eznft:latest"
            - --args
            - "--target-override=https://example.com"
